backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/posts.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - {
          label: "Template Engine",
          name: "templateEngineOverride",
          widget: "string",
          default: "njk, md",
        }
      # - {label: "Body", name: "body", widget: "markdown"}
