backend:
  name: git-gateway
  repo: GalanCM/static-blog
  branch: cms

# publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date Published", name: "date", widget: "date" }
      - { label: "Date Modified", name: "modified", widget: "date" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          options: [{ label: "Post", value: "layouts/posts.njk" }],
          default: "layouts/posts.njk",
        }
      - { label: "Body", name: "body", widget: "markdown" }
